#! /bin/bash


echo "O próximo comando vai apagar seu cache de pacotes, mas apenas as coisas não instaladas"

sudo pacman -Sc -s -s; clear

echo "Não precisa disso toda vez, masok"

sudo pacman -Qtdq && sudo pacman -Rns $(pacman -Qtdq); clear

echo "limpando seu cache, seu porco."

sudo du -sh ~/.cache/ && rm -rf ~/.cache/* && clear

echo "Terminamos a faxina com merda acumulada por séculos ;)"
echo "Meu nome é Luís, obrigado por usar este script ;)"
