#! /bin/bash

echo "Parte mais chata é esperar, concorda? ##

sudo pacman -Syy; clear

echo "O próximo comando vai apagar seu cache de pacotes, mas apenas as coisas não instaladas"

sudo pacman -Sc -y -y; clear

echo "Não precisa disso toda vez, masok"

sudo pacman -Qtdq && sudo pacman -Rns $(pacman -Qtdq); clear

echo "limpando seu cache, seu porco."

sudo du -sh ~/.cache/ && rm -rf ~/.cache/* && clear


